version: "3"
services:
  # Api Service
  task-app-api:
    ports:
      - "8000:8000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - task-app-mysql
    image: "tusharguliany/task-app"

  # Database Service (Mysql)
  task-app-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: task-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - e:\docker_data\mongo\volume:/data/db