spring:
  profiles:    active:    - prod  jpa:
    hibernate:      ddl-auto: update    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        
server:  port: 8000